-- Operational modules that previously existed only as static demo dashboards.
-- All records are tenant-scoped by school_id and protected with RLS.

create table if not exists public.payroll_records (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  employee_name text not null,
  employee_role text,
  pay_period text not null,
  basic_salary numeric(12,2) not null default 0 check (basic_salary >= 0),
  allowances numeric(12,2) not null default 0 check (allowances >= 0),
  deductions numeric(12,2) not null default 0 check (deductions >= 0),
  status text not null default 'pending',
  paid_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.transport_vehicles (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  vehicle_number text not null,
  route_name text,
  driver_name text,
  driver_phone text,
  capacity integer not null default 0 check (capacity >= 0),
  status text not null default 'active',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (school_id, vehicle_number)
);

create table if not exists public.inventory_items (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  name text not null,
  category text,
  quantity integer not null default 0 check (quantity >= 0),
  unit text,
  reorder_level integer not null default 0 check (reorder_level >= 0),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.hostel_rooms (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  hostel_name text not null,
  room_number text not null,
  capacity integer not null default 0 check (capacity >= 0),
  occupied integer not null default 0 check (occupied >= 0),
  warden_name text,
  status text not null default 'active',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (school_id, hostel_name, room_number),
  check (occupied <= capacity)
);

create index if not exists idx_payroll_records_school_id on public.payroll_records(school_id);
create index if not exists idx_transport_vehicles_school_id on public.transport_vehicles(school_id);
create index if not exists idx_inventory_items_school_id on public.inventory_items(school_id);
create index if not exists idx_hostel_rooms_school_id on public.hostel_rooms(school_id);

alter table public.payroll_records enable row level security;
alter table public.transport_vehicles enable row level security;
alter table public.inventory_items enable row level security;
alter table public.hostel_rooms enable row level security;

-- School members can read their school's operational records.
do $$
declare
  t text;
begin
  foreach t in array array['payroll_records','transport_vehicles','inventory_items','hostel_rooms'] loop
    execute format('drop policy if exists %I on public.%I', t || '_select_school', t);
    execute format(
      'create policy %I on public.%I for select to authenticated using (school_id = public.get_my_school_id())',
      t || '_select_school', t
    );

    execute format('drop policy if exists %I on public.%I', t || '_insert_admin', t);
    execute format(
      'create policy %I on public.%I for insert to authenticated with check (school_id = public.get_my_school_id() and exists (select 1 from public.profiles p where p.id = auth.uid() and p.school_id = school_id and lower(coalesce(p.role, '''')) in (''principal'',''staff'') and coalesce(p.is_active, true)))',
      t || '_insert_admin', t
    );

    execute format('drop policy if exists %I on public.%I', t || '_update_admin', t);
    execute format(
      'create policy %I on public.%I for update to authenticated using (school_id = public.get_my_school_id() and exists (select 1 from public.profiles p where p.id = auth.uid() and p.school_id = school_id and lower(coalesce(p.role, '''')) in (''principal'',''staff'') and coalesce(p.is_active, true))) with check (school_id = public.get_my_school_id())',
      t || '_update_admin', t
    );

    execute format('drop policy if exists %I on public.%I', t || '_delete_admin', t);
    execute format(
      'create policy %I on public.%I for delete to authenticated using (school_id = public.get_my_school_id() and exists (select 1 from public.profiles p where p.id = auth.uid() and p.school_id = school_id and lower(coalesce(p.role, '''')) in (''principal'',''staff'') and coalesce(p.is_active, true)))',
      t || '_delete_admin', t
    );
  end loop;
end $$;
