-- Phase 1: homework/assignment date ranges, targeted students, parent links,
-- and parent-specific work notifications.

alter table public.assignments
  add column if not exists work_type text not null default 'assignment',
  add column if not exists start_date date,
  add column if not exists audience text not null default 'class';

update public.assignments
set start_date = coalesce(start_date, assigned_date, current_date)
where start_date is null;

alter table public.assignments
  alter column start_date set default current_date;

alter table public.assignments
  alter column start_date set not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'assignments_work_type_check'
      and conrelid = 'public.assignments'::regclass
  ) then
    alter table public.assignments
      add constraint assignments_work_type_check
      check (work_type in ('assignment','homework'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'assignments_audience_check'
      and conrelid = 'public.assignments'::regclass
  ) then
    alter table public.assignments
      add constraint assignments_audience_check
      check (audience in ('class','students'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'assignments_date_range_check'
      and conrelid = 'public.assignments'::regclass
  ) then
    alter table public.assignments
      add constraint assignments_date_range_check
      check (due_date is null or due_date >= start_date);
  end if;
end $$;

create index if not exists idx_assignments_school_type_dates
  on public.assignments (school_id, work_type, start_date, due_date);

create table if not exists public.assignment_students (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  assignment_id bigint not null references public.assignments(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (assignment_id, student_id)
);

create index if not exists idx_assignment_students_assignment
  on public.assignment_students (assignment_id);
create index if not exists idx_assignment_students_student
  on public.assignment_students (student_id);
create index if not exists idx_assignment_students_school
  on public.assignment_students (school_id);

alter table public.assignment_students enable row level security;

create table if not exists public.parent_student_links (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  parent_id uuid not null references public.profiles(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade,
  relationship text not null default 'parent',
  created_at timestamptz not null default now(),
  unique (parent_id, student_id)
);

create index if not exists idx_parent_student_links_parent
  on public.parent_student_links (parent_id);
create index if not exists idx_parent_student_links_student
  on public.parent_student_links (student_id);
create index if not exists idx_parent_student_links_school
  on public.parent_student_links (school_id);

alter table public.parent_student_links enable row level security;

-- Backfill parent/student links from the existing parent_email convention.
insert into public.parent_student_links (school_id, parent_id, student_id)
select s.school_id, p.id, s.id
from public.students s
join public.profiles p
  on p.school_id = s.school_id
 and lower(trim(coalesce(p.email,''))) = lower(trim(coalesce(s.parent_email,'')))
where lower(coalesce(p.role,'')) = 'parent'
  and coalesce(p.is_active,true)
  and nullif(trim(coalesce(s.parent_email,'')), '') is not null
on conflict (parent_id, student_id) do nothing;

create or replace function private.parent_can_access_student(p_student_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.students s
    where s.id = p_student_id
      and s.school_id = (select private.current_school_id())
      and (
        exists (
          select 1
          from public.parent_student_links l
          where l.school_id = s.school_id
            and l.student_id = s.id
            and l.parent_id = (select auth.uid())
        )
        or lower(trim(coalesce(s.parent_email,''))) =
           lower(trim(coalesce((select auth.jwt()->>'email'),'')))
      )
  )
$$;

create or replace function private.parent_can_access_class(p_class text, p_section text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.students s
    where s.school_id = (select private.current_school_id())
      and lower(trim(coalesce(s.class_name,''))) = lower(trim(coalesce(p_class,'')))
      and (
        nullif(trim(coalesce(p_section,'')), '') is null
        or lower(trim(coalesce(s.section_name,''))) = lower(trim(coalesce(p_section,'')))
      )
      and (select private.parent_can_access_student(s.id))
  )
$$;

create or replace function private.parent_can_access_assignment(p_assignment_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.assignments a
    where a.id = p_assignment_id
      and a.school_id = (select private.current_school_id())
      and (
        (
          coalesce(a.audience,'class') = 'class'
          and (select private.parent_can_access_class(a.assigned_class, a.assigned_section))
        )
        or
        (
          a.audience = 'students'
          and exists (
            select 1
            from public.assignment_students x
            where x.assignment_id = a.id
              and x.school_id = a.school_id
              and (select private.parent_can_access_student(x.student_id))
          )
        )
      )
  )
$$;

-- Replace the assignment SELECT policy so student-targeted work is not visible
-- to parents whose children are only classmates of the target student.
drop policy if exists assignments_select_role_scoped on public.assignments;
create policy assignments_select_role_scoped
on public.assignments
for select
to authenticated
using (
  (
    school_id = (select private.current_school_id())
    and (select private.is_school_admin())
  )
  or
  (
    school_id = (select private.current_school_id())
    and (select private."current_role"()) = 'teacher'
    and (
      created_by = (select auth.uid())
      or (select private.teacher_can_access_class(assignments.assigned_class, assignments.assigned_section))
    )
  )
  or
  (
    school_id = (select private.current_school_id())
    and (select private."current_role"()) = 'parent'
    and (select private.parent_can_access_assignment(assignments.id))
  )
);

-- Assignment/student target policies.
drop policy if exists assignment_students_select_scoped on public.assignment_students;
create policy assignment_students_select_scoped
on public.assignment_students
for select
to authenticated
using (
  school_id = (select private.current_school_id())
  and (
    (select private.is_school_admin())
    or (select private.teacher_can_access_student(student_id))
    or (select private.parent_can_access_student(student_id))
  )
);

drop policy if exists assignment_students_insert_manager on public.assignment_students;
create policy assignment_students_insert_manager
on public.assignment_students
for insert
to authenticated
with check (
  school_id = (select private.current_school_id())
  and exists (
    select 1
    from public.assignments a
    where a.id = assignment_id
      and a.school_id = assignment_students.school_id
      and (
        (select private.is_school_admin())
        or (
          (select private."current_role"()) = 'teacher'
          and a.created_by = (select auth.uid())
          and (select private.teacher_can_access_student(student_id))
        )
      )
  )
);

drop policy if exists assignment_students_delete_manager on public.assignment_students;
create policy assignment_students_delete_manager
on public.assignment_students
for delete
to authenticated
using (
  school_id = (select private.current_school_id())
  and exists (
    select 1
    from public.assignments a
    where a.id = assignment_id
      and a.school_id = assignment_students.school_id
      and (
        (select private.is_school_admin())
        or (
          (select private."current_role"()) = 'teacher'
          and a.created_by = (select auth.uid())
        )
      )
  )
);

-- Parent/student link policies. Parents only see their own links; admins manage school links.
drop policy if exists parent_student_links_select_scoped on public.parent_student_links;
create policy parent_student_links_select_scoped
on public.parent_student_links
for select
to authenticated
using (
  school_id = (select private.current_school_id())
  and (
    parent_id = (select auth.uid())
    or (select private.is_school_admin())
  )
);

drop policy if exists parent_student_links_insert_admin on public.parent_student_links;
create policy parent_student_links_insert_admin
on public.parent_student_links
for insert
to authenticated
with check (
  school_id = (select private.current_school_id())
  and (select private.is_school_admin())
);

drop policy if exists parent_student_links_update_admin on public.parent_student_links;
create policy parent_student_links_update_admin
on public.parent_student_links
for update
to authenticated
using (
  school_id = (select private.current_school_id())
  and (select private.is_school_admin())
)
with check (
  school_id = (select private.current_school_id())
  and (select private.is_school_admin())
);

drop policy if exists parent_student_links_delete_admin on public.parent_student_links;
create policy parent_student_links_delete_admin
on public.parent_student_links
for delete
to authenticated
using (
  school_id = (select private.current_school_id())
  and (select private.is_school_admin())
);

-- Keep links in sync when a student points at a parent email.
create or replace function public.sync_student_parent_link()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_parent_id uuid;
begin
  if nullif(trim(coalesce(new.parent_email,'')), '') is null then
    return new;
  end if;

  select p.id into v_parent_id
  from public.profiles p
  where p.school_id = new.school_id
    and lower(trim(coalesce(p.email,''))) = lower(trim(new.parent_email))
    and lower(coalesce(p.role,'')) = 'parent'
    and coalesce(p.is_active,true)
  limit 1;

  if v_parent_id is not null then
    insert into public.parent_student_links (school_id, parent_id, student_id)
    values (new.school_id, v_parent_id, new.id)
    on conflict (parent_id, student_id) do nothing;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_sync_student_parent_link on public.students;
create trigger trg_sync_student_parent_link
after insert or update of parent_email, school_id
on public.students
for each row execute function public.sync_student_parent_link();

-- When a parent profile is created after the student, backfill all matching children.
create or replace function public.sync_parent_profile_children()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if lower(coalesce(new.role,'')) = 'parent'
     and coalesce(new.is_active,true)
     and new.school_id is not null
     and nullif(trim(coalesce(new.email,'')), '') is not null then
    insert into public.parent_student_links (school_id, parent_id, student_id)
    select s.school_id, new.id, s.id
    from public.students s
    where s.school_id = new.school_id
      and lower(trim(coalesce(s.parent_email,''))) = lower(trim(new.email))
    on conflict (parent_id, student_id) do nothing;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_sync_parent_profile_children on public.profiles;
create trigger trg_sync_parent_profile_children
after insert or update of email, role, school_id, is_active
on public.profiles
for each row execute function public.sync_parent_profile_children();

-- Parent-specific notifications for homework/assignments.
create table if not exists public.parent_work_notifications (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  parent_id uuid not null references public.profiles(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade,
  assignment_id bigint not null references public.assignments(id) on delete cascade,
  title text not null,
  message text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  unique (parent_id, student_id, assignment_id)
);

create index if not exists idx_parent_work_notifications_parent
  on public.parent_work_notifications (parent_id, is_read, created_at desc);
create index if not exists idx_parent_work_notifications_assignment
  on public.parent_work_notifications (assignment_id);

alter table public.parent_work_notifications enable row level security;

drop policy if exists parent_work_notifications_select_own on public.parent_work_notifications;
create policy parent_work_notifications_select_own
on public.parent_work_notifications
for select
to authenticated
using (
  parent_id = (select auth.uid())
  and school_id = (select private.current_school_id())
);

drop policy if exists parent_work_notifications_update_own on public.parent_work_notifications;
create policy parent_work_notifications_update_own
on public.parent_work_notifications
for update
to authenticated
using (
  parent_id = (select auth.uid())
  and school_id = (select private.current_school_id())
)
with check (
  parent_id = (select auth.uid())
  and school_id = (select private.current_school_id())
);

create or replace function public.refresh_school_work_parent_notifications(p_assignment_id bigint)
returns integer
language plpgsql
security definer
set search_path = public, private
set row_security = off
as $$
declare
  v_uid uuid := auth.uid();
  v_assignment public.assignments%rowtype;
  v_count integer := 0;
begin
  if v_uid is null then
    raise exception 'Not authenticated';
  end if;

  select * into v_assignment
  from public.assignments
  where id = p_assignment_id
    and school_id = private.current_school_id();

  if not found then
    raise exception 'School work record not found';
  end if;

  if not private.is_school_admin()
     and not (private."current_role"() = 'teacher' and v_assignment.created_by = v_uid) then
    raise exception 'Not authorized';
  end if;

  delete from public.parent_work_notifications
  where assignment_id = p_assignment_id;

  insert into public.parent_work_notifications (
    school_id, parent_id, student_id, assignment_id, title, message
  )
  select distinct
    v_assignment.school_id,
    l.parent_id,
    s.id,
    v_assignment.id,
    case when v_assignment.work_type = 'homework' then 'New Homework' else 'New Assignment' end,
    s.full_name || ' (' || coalesce(s.class_name,'') ||
      case when nullif(trim(coalesce(s.section_name,'')), '') is null then '' else '-' || s.section_name end ||
      ') received ' || coalesce(v_assignment.subject,'school work') || ': ' || v_assignment.title ||
      '. Due: ' || coalesce(to_char(v_assignment.due_date,'DD Mon YYYY'),'No due date')
  from public.students s
  join public.parent_student_links l
    on l.student_id = s.id and l.school_id = s.school_id
  where s.school_id = v_assignment.school_id
    and coalesce(s.is_active,true)
    and (
      (
        v_assignment.audience = 'class'
        and lower(trim(coalesce(s.class_name,''))) = lower(trim(coalesce(v_assignment.assigned_class,'')))
        and (
          nullif(trim(coalesce(v_assignment.assigned_section,'')), '') is null
          or lower(trim(coalesce(s.section_name,''))) = lower(trim(coalesce(v_assignment.assigned_section,'')))
        )
      )
      or
      (
        v_assignment.audience = 'students'
        and exists (
          select 1 from public.assignment_students x
          where x.assignment_id = v_assignment.id
            and x.student_id = s.id
            and x.school_id = v_assignment.school_id
        )
      )
    )
  on conflict (parent_id, student_id, assignment_id) do update
    set title = excluded.title,
        message = excluded.message,
        is_read = false,
        created_at = now();

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

grant execute on function public.refresh_school_work_parent_notifications(bigint) to authenticated;
