-- Fee and challan foundation. Safe to run after the existing school/student tables.
create extension if not exists pgcrypto;

create table if not exists public.fee_categories (
  id bigint generated by default as identity primary key,
  school_id integer not null references public.schools(id) on delete cascade,
  name text not null,
  amount numeric(12,2) not null default 0 check (amount >= 0),
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (school_id, name)
);

create table if not exists public.student_fees (
  id bigint generated by default as identity primary key,
  school_id integer not null references public.schools(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade,
  fee_category_id bigint references public.fee_categories(id) on delete set null,
  amount numeric(12,2) not null check (amount >= 0),
  due_date date not null,
  fee_month date not null,
  status text not null default 'unpaid' check (status in ('unpaid','partial','paid','cancelled')),
  created_at timestamptz not null default now(),
  unique (student_id, fee_category_id, fee_month)
);

create table if not exists public.fee_payments (
  id bigint generated by default as identity primary key,
  school_id integer not null references public.schools(id) on delete cascade,
  student_fee_id bigint not null references public.student_fees(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade,
  amount numeric(12,2) not null check (amount > 0),
  payment_date timestamptz not null default now(),
  payment_method text not null default 'cash',
  receipt_number text not null unique,
  notes text,
  status text not null default 'paid' check (status in ('paid','void')),
  created_at timestamptz not null default now()
);

create index if not exists idx_student_fees_school_month on public.student_fees(school_id, fee_month);
create index if not exists idx_fee_payments_school_date on public.fee_payments(school_id, payment_date);

alter table public.fee_categories enable row level security;
alter table public.student_fees enable row level security;
alter table public.fee_payments enable row level security;

do $$
declare t text;
begin
  foreach t in array array['fee_categories','student_fees','fee_payments'] loop
    execute format('drop policy if exists %I on public.%I', t || '_school_access', t);
    execute format($p$
      create policy %I on public.%I for all to authenticated
      using (school_id = (select p.school_id from public.profiles p where p.id = auth.uid()))
      with check (school_id = (select p.school_id from public.profiles p where p.id = auth.uid()))
    $p$, t || '_school_access', t);
  end loop;
end $$;

create or replace function public.generate_monthly_student_fees(p_fee_month date)
returns integer
language plpgsql
security invoker
set search_path = public
as $$
declare v_school integer; v_count integer := 0; v_inserted integer := 0; v_category record;
begin
  select school_id into v_school from profiles where id = auth.uid();
  if v_school is null then raise exception 'School profile is not linked'; end if;
  for v_category in select id, amount from fee_categories where school_id = v_school and is_active loop
    insert into student_fees(school_id,student_id,fee_category_id,amount,due_date,fee_month)
    select v_school,s.id,v_category.id,v_category.amount,
           (p_fee_month + interval '10 days')::date,p_fee_month
    from students s where s.school_id=v_school and coalesce(s.is_active,true)
    on conflict (student_id,fee_category_id,fee_month) do nothing;
    get diagnostics v_inserted = row_count;\n    v_count := v_count + v_inserted;
  end loop;
  return v_count;
end $$;

create or replace function public.record_fee_payment(
  p_student_fee_id bigint,
  p_amount numeric,
  p_payment_method text default 'cash',
  p_notes text default null
)
returns table(receipt_number text, payment_id bigint)
language plpgsql
security invoker
set search_path = public
as $$
declare v_school integer; v_student bigint; v_balance numeric; v_receipt text;
begin
  select school_id,student_id into v_school,v_student from student_fees where id=p_student_fee_id;
  if v_school is null or v_school <> (select school_id from profiles where id=auth.uid()) then raise exception 'Fee record not accessible'; end if;
  if p_amount <= 0 then raise exception 'Payment must be greater than zero'; end if;
  select greatest(sf.amount - coalesce((select sum(fp.amount) from fee_payments fp where fp.student_fee_id=sf.id and fp.status='paid'),0),0)
    into v_balance from student_fees sf where sf.id=p_student_fee_id;
  if p_amount > v_balance then raise exception 'Payment exceeds remaining balance'; end if;
  v_receipt := 'RCPT-' || to_char(clock_timestamp(),'YYYYMMDDHH24MISSMS') || '-' || floor(random()*1000)::int;
  insert into fee_payments(school_id,student_fee_id,student_id,amount,payment_method,receipt_number,notes)
    values(v_school,p_student_fee_id,v_student,p_amount,coalesce(nullif(p_payment_method,''),'cash'),v_receipt,p_notes)
    returning fee_payments.receipt_number, fee_payments.id into v_receipt,payment_id;
  update student_fees sf set status=case when v_balance-p_amount <= 0 then 'paid' else 'partial' end where sf.id=p_student_fee_id;
  receipt_number := v_receipt; return next;
end $$;

grant execute on function public.generate_monthly_student_fees(date) to authenticated;
grant execute on function public.record_fee_payment(bigint,numeric,text,text) to authenticated;
