-- Persist demo subscriptions, plan requests and independently payable challans.
create table if not exists public.school_subscriptions (
  id bigint generated by default as identity primary key,
  school_id integer not null unique references public.schools(id) on delete cascade,
  plan_key text not null default 'demo',
  status text not null default 'demo' check (status in ('demo','active','expired','cancelled')),
  trial_started_at timestamptz,
  trial_ends_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.subscription_plan_requests (
  id bigint generated by default as identity primary key,
  school_id integer not null references public.schools(id) on delete cascade,
  requested_by uuid not null references auth.users(id) on delete cascade,
  plan_key text not null check (plan_key in ('starter','pro','premium_custom','custom_budget')),
  status text not null default 'pending' check (status in ('pending','contacted','approved','declined')),
  created_at timestamptz not null default now()
);
alter table public.school_subscriptions enable row level security;
alter table public.subscription_plan_requests enable row level security;
drop policy if exists school_subscriptions_school_read on public.school_subscriptions;
create policy school_subscriptions_school_read on public.school_subscriptions
for select to authenticated using (school_id = (select p.school_id from public.profiles p where p.id=auth.uid()));
drop policy if exists subscription_plan_requests_school_read on public.subscription_plan_requests;
create policy subscription_plan_requests_school_read on public.subscription_plan_requests
for select to authenticated using (school_id = (select p.school_id from public.profiles p where p.id=auth.uid()));
grant select on public.school_subscriptions, public.subscription_plan_requests to authenticated;

create or replace function public.start_school_demo()
returns public.school_subscriptions
language plpgsql
security definer
set search_path = public
as $$
declare v_uid uuid := auth.uid(); v_school integer; v_result public.school_subscriptions;
begin
  if v_uid is null then raise exception 'Not authenticated'; end if;
  select school_id into v_school from public.profiles where id=v_uid and is_active=true and role='principal';
  if v_school is null then raise exception 'Only an active principal can start the school demo'; end if;
  insert into public.school_subscriptions(school_id,plan_key,status,trial_started_at,trial_ends_at)
  values(v_school,'demo','demo',now(),now()+interval '2 days')
  on conflict(school_id) do nothing;
  select * into v_result from public.school_subscriptions where school_id=v_school;
  if v_result.status <> 'demo' or v_result.trial_ends_at <= now() then
    raise exception 'The free demo has already ended';
  end if;
  return v_result;
end $$;
revoke all on function public.start_school_demo() from public, anon;
grant execute on function public.start_school_demo() to authenticated;

create or replace function public.request_subscription_plan(p_plan_key text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare v_uid uuid := auth.uid(); v_school integer; v_request bigint;
begin
  if v_uid is null then raise exception 'Not authenticated'; end if;
  select school_id into v_school from public.profiles
   where id=v_uid and is_active=true and role in ('principal','staff');
  if v_school is null then raise exception 'Only active school staff can request a plan'; end if;
  if p_plan_key not in ('starter','pro','premium_custom','custom_budget') then
    raise exception 'Unknown subscription plan';
  end if;
  insert into public.subscription_plan_requests(school_id,requested_by,plan_key)
  values(v_school,v_uid,p_plan_key) returning id into v_request;
  return v_request;
end $$;
revoke all on function public.request_subscription_plan(text) from public, anon;
grant execute on function public.request_subscription_plan(text) to authenticated;

create table if not exists public.school_challans (
  id bigint generated by default as identity primary key,
  school_id integer not null references public.schools(id) on delete cascade,
  challan_number text unique,
  challan_type text not null,
  reference text,
  amount numeric(12,2) not null check(amount > 0),
  paid_amount numeric(12,2) not null default 0 check(paid_amount >= 0 and paid_amount <= amount),
  due_date date not null,
  status text not null default 'unpaid' check(status in ('unpaid','partial','paid','void')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.school_challan_payments (
  id bigint generated by default as identity primary key,
  school_id integer not null references public.schools(id) on delete cascade,
  challan_id bigint not null references public.school_challans(id) on delete cascade,
  amount numeric(12,2) not null check(amount > 0),
  payment_method text not null default 'cash',
  receipt_number text not null unique,
  paid_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);
create index if not exists idx_school_challans_school_due on public.school_challans(school_id,due_date);
create index if not exists idx_school_challan_payments_challan on public.school_challan_payments(challan_id);
alter table public.school_challans enable row level security;
alter table public.school_challan_payments enable row level security;
drop policy if exists school_challans_school_read on public.school_challans;
create policy school_challans_school_read on public.school_challans
for select to authenticated using (school_id=(select p.school_id from public.profiles p where p.id=auth.uid()));
drop policy if exists school_challans_school_write on public.school_challans;
create policy school_challans_school_write on public.school_challans
for all to authenticated
using (school_id=(select p.school_id from public.profiles p where p.id=auth.uid()) and exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('principal','staff') and coalesce(p.is_active,true)))
with check (school_id=(select p.school_id from public.profiles p where p.id=auth.uid()) and exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('principal','staff') and coalesce(p.is_active,true)));
drop policy if exists school_challan_payments_school_read on public.school_challan_payments;
create policy school_challan_payments_school_read on public.school_challan_payments
for select to authenticated using (school_id=(select p.school_id from public.profiles p where p.id=auth.uid()));
drop policy if exists school_challan_payments_school_write on public.school_challan_payments;
create policy school_challan_payments_school_write on public.school_challan_payments
for all to authenticated
using (school_id=(select p.school_id from public.profiles p where p.id=auth.uid()) and exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('principal','staff') and coalesce(p.is_active,true)))
with check (school_id=(select p.school_id from public.profiles p where p.id=auth.uid()) and exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('principal','staff') and coalesce(p.is_active,true)));
grant select,insert,update,delete on public.school_challans,public.school_challan_payments to authenticated;
grant usage,select on sequence public.school_challans_id_seq,public.school_challan_payments_id_seq to authenticated;

create or replace function public.set_school_challan_number()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if new.challan_number is null then new.challan_number := 'CH-'||to_char(current_date,'YYYYMMDD')||'-'||lpad(new.id::text,6,'0'); end if;
  return new;
end $$;
-- identity ids are assigned before BEFORE INSERT triggers
drop trigger if exists trg_school_challan_number on public.school_challans;
create trigger trg_school_challan_number before insert on public.school_challans
for each row execute function public.set_school_challan_number();
revoke all on function public.set_school_challan_number() from public,anon,authenticated;

create or replace function public.record_school_challan_payment(p_challan_id bigint,p_amount numeric,p_payment_method text default 'cash')
returns table(payment_id bigint,receipt_number text,new_status text)
language plpgsql security definer set search_path=public set row_security=off as $$
declare v_uid uuid:=auth.uid(); v_school integer; v_row public.school_challans%rowtype; v_payment bigint; v_receipt text; v_paid numeric;
begin
  if v_uid is null then raise exception 'Not authenticated'; end if;
  select school_id into v_school from public.profiles where id=v_uid and is_active=true and role in ('principal','staff');
  if v_school is null then raise exception 'Only active school staff can record payments'; end if;
  select * into v_row from public.school_challans where id=p_challan_id and school_id=v_school for update;
  if not found or v_row.status='void' then raise exception 'Challan not found or is void'; end if;
  if p_amount is null or p_amount<=0 then raise exception 'Payment must be greater than zero'; end if;
  if v_row.paid_amount+p_amount>v_row.amount then raise exception 'Payment exceeds remaining balance'; end if;
  insert into public.school_challan_payments(school_id,challan_id,amount,payment_method,receipt_number,created_by)
  values(v_school,p_challan_id,p_amount,coalesce(nullif(trim(p_payment_method),''),'cash'),'CHRC-'||to_char(clock_timestamp(),'YYYYMMDDHH24MISSMS')||'-'||p_challan_id,v_uid)
  returning id,school_challan_payments.receipt_number into v_payment,v_receipt;
  v_paid:=v_row.paid_amount+p_amount;
  update public.school_challans set paid_amount=v_paid,status=case when v_paid>=amount then 'paid' else 'partial' end,updated_at=now() where id=p_challan_id;
  return query select v_payment,v_receipt,case when v_paid>=v_row.amount then 'paid' else 'partial' end;
end $$;
revoke all on function public.record_school_challan_payment(bigint,numeric,text) from public,anon;
grant execute on function public.record_school_challan_payment(bigint,numeric,text) to authenticated;
