-- Add a school scoped income and expense ledger for the Accounting screen.
create table if not exists public.accounting_entries (
  id bigint generated by default as identity primary key,
  school_id integer not null references public.schools(id) on delete cascade,
  description text not null,
  entry_type text not null check (entry_type in ('income','expense')),
  category text not null,
  amount numeric(12,2) not null check (amount >= 0),
  entry_date date not null default current_date,
  payment_method text check (payment_method is null or payment_method in ('cash','bank','cheque','online')),
  reference_no text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_accounting_entries_school_date on public.accounting_entries(school_id,entry_date desc);
alter table public.accounting_entries enable row level security;
drop policy if exists accounting_entries_school_read on public.accounting_entries;
create policy accounting_entries_school_read on public.accounting_entries
for select to authenticated
using (school_id = (select p.school_id from public.profiles p where p.id = auth.uid()));
drop policy if exists accounting_entries_school_write on public.accounting_entries;
create policy accounting_entries_school_write on public.accounting_entries
for all to authenticated
using (
  school_id = (select p.school_id from public.profiles p where p.id = auth.uid())
  and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('principal','staff') and coalesce(p.is_active,true))
)
with check (
  school_id = (select p.school_id from public.profiles p where p.id = auth.uid())
  and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('principal','staff') and coalesce(p.is_active,true))
);
grant select,insert,update,delete on public.accounting_entries to authenticated;
grant usage,select on sequence public.accounting_entries_id_seq to authenticated;
