-- HADI SMS: Leave Management
create table if not exists public.leave_requests (
  id bigint generated by default as identity primary key,
  school_id integer not null references public.schools(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  leave_type text not null,
  start_date date not null,
  end_date date not null,
  reason text not null,
  status text not null default 'pending',
  approved_by uuid references auth.users(id) on delete set null,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint leave_requests_date_check check (end_date >= start_date),
  constraint leave_requests_status_check check (status in ('pending','approved','rejected','cancelled')),
  constraint leave_requests_type_check check (length(trim(leave_type)) > 0),
  constraint leave_requests_reason_check check (length(trim(reason)) > 0)
);
create index if not exists idx_leave_requests_school_dates on public.leave_requests (school_id, start_date desc);
create index if not exists idx_leave_requests_user on public.leave_requests (user_id, created_at desc);
alter table public.leave_requests enable row level security;
drop policy if exists "leave_select_school" on public.leave_requests;
create policy "leave_select_school" on public.leave_requests for select to authenticated using (school_id = (select p.school_id from public.profiles p where p.id = auth.uid()));
drop policy if exists "leave_insert_own" on public.leave_requests;
create policy "leave_insert_own" on public.leave_requests for insert to authenticated with check (school_id = (select p.school_id from public.profiles p where p.id = auth.uid()) and user_id = auth.uid() and status = 'pending');
drop policy if exists "leave_update_own_pending" on public.leave_requests;
create policy "leave_update_own_pending" on public.leave_requests for update to authenticated using (school_id = (select p.school_id from public.profiles p where p.id = auth.uid()) and user_id = auth.uid() and status = 'pending') with check (school_id = (select p.school_id from public.profiles p where p.id = auth.uid()) and user_id = auth.uid() and status = 'pending');
drop policy if exists "leave_manage_principal_staff" on public.leave_requests;
create policy "leave_manage_principal_staff" on public.leave_requests for update to authenticated using (school_id = (select p.school_id from public.profiles p where p.id = auth.uid()) and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('principal','staff'))) with check (school_id = (select p.school_id from public.profiles p where p.id = auth.uid()) and status in ('pending','approved','rejected','cancelled'));
drop policy if exists "leave_delete_own_pending" on public.leave_requests;
create policy "leave_delete_own_pending" on public.leave_requests for delete to authenticated using (school_id = (select p.school_id from public.profiles p where p.id = auth.uid()) and user_id = auth.uid() and status = 'pending');
drop policy if exists "leave_delete_principal_staff" on public.leave_requests;
create policy "leave_delete_principal_staff" on public.leave_requests for delete to authenticated using (school_id = (select p.school_id from public.profiles p where p.id = auth.uid()) and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('principal','staff')));
create or replace function public.set_leave_requests_updated_at() returns trigger language plpgsql security invoker set search_path = public as $ begin new.updated_at = now(); return new; end; $$;
drop trigger if exists trg_leave_requests_updated_at on public.leave_requests;
create trigger trg_leave_requests_updated_at before update on public.leave_requests for each row execute function public.set_leave_requests_updated_at();
revoke all on function public.set_leave_requests_updated_at() from public;